# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Make port 3000 available
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "run", "dev", "--", "--host"]
